if(BUILD_TEST)
    enable_testing()
endif()
if(NOT BUILD_TEST)
    akt_exclude_targets_in(${CMAKE_SOURCE_DIR}/src/test)
endif()
if(NOT BUILD_EXAMPLE)
    akt_exclude_targets_in(${CMAKE_SOURCE_DIR}/src/example)
endif()
akt_add_targets_in(${CMAKE_SOURCE_DIR}/src)